import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import { FcGoogle } from "react-icons/fc";

const Login: NextPage = () => {
  const user = useSession().data?.user;
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen max-w-[100vw] flex-col items-center justify-center overflow-x-hidden">
        <div className="flex h-[250px] flex-col space-x-3">
          <button
            onClick={() => signIn("google")}
            className="flex w-full items-center space-x-2 rounded-lg bg-[#2e2e2e] px-6 py-3"
          >
            <FcGoogle className="h-6 w-6 text-white" />
            <span>Login with Google</span>
          </button>
        </div>
      </main>
    </>
  );
};

export default Login;
