import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import Navbar from "~/components/navbar/Navbar";
import MobileBottomBar from "~/components/mobileBottomBar/MobileBottomBar";
import ResutsRow from "~/components/resultsRow/ResultsRow";
import requests from "~/utils/requests";

const Search: NextPage = ({ highlighted, trending }: any) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center overflow-x-hidden">
        <Navbar />

        <MobileBottomBar />
      </main>
    </>
  );
};

export default Search;
