import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import Navbar from "~/components/navbar/Navbar";
import MobileBottomBar from "~/components/mobileBottomBar/MobileBottomBar";

const Search: NextPage = () => {
  const onChange = ({ currentTarget }: React.ChangeEvent<HTMLInputElement>) =>
    console.log(currentTarget.value);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mt-[70px] flex min-h-[calc(100vh-70px)] flex-col items-center justify-start overflow-x-hidden">
        <Navbar />
        <div>
          <input onChange={onChange} />
        </div>
        <MobileBottomBar />
      </main>
    </>
  );
};

export default Search;
